// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSB27D9_MW5733_61DYEBjGon_0hz4rm0',
    appId: '1:702700694891:web:dd24481129cfd1f04d702e',
    messagingSenderId: '702700694891',
    projectId: 'vyroba-vecicky-test',
    authDomain: 'vyroba-vecicky-test.firebaseapp.com',
    databaseURL: 'https://vyroba-vecicky-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vyroba-vecicky-test.appspot.com',
    measurementId: 'G-FR92653RND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoIcHT094YLtJXomnjZcOPKfFGByuSl6Y',
    appId: '1:702700694891:android:7d0e068a05ab35b74d702e',
    messagingSenderId: '702700694891',
    projectId: 'vyroba-vecicky-test',
    databaseURL: 'https://vyroba-vecicky-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vyroba-vecicky-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEm7PF_zc4nIVagxe0IXlAHHghQJnuiYA',
    appId: '1:702700694891:ios:43e2bab764696d6d4d702e',
    messagingSenderId: '702700694891',
    projectId: 'vyroba-vecicky-test',
    databaseURL: 'https://vyroba-vecicky-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vyroba-vecicky-test.appspot.com',
    iosBundleId: 'com.example.eTelka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEm7PF_zc4nIVagxe0IXlAHHghQJnuiYA',
    appId: '1:702700694891:ios:0fa3db24f42adc204d702e',
    messagingSenderId: '702700694891',
    projectId: 'vyroba-vecicky-test',
    databaseURL: 'https://vyroba-vecicky-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vyroba-vecicky-test.appspot.com',
    iosBundleId: 'com.example.eTelka.RunnerTests',
  );
}
